<% if defined?(JRUBY_VERSION) %>
<% require 'ext/mysql-connector-java-5.1.7-bin.jar' %>
<% end %>

development:
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbc
  username: root
  password: 
  url: jdbc:mysql://localhost/kompetansesok_development<%= ENV['DB_SUFFIX'] %>
  driver: org.gjt.mm.mysql.Driver
<% else %>
  adapter: mysql
  encoding: utf8
  database: kompetansesok_development<%= ENV['DB_SUFFIX'] %>
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
<% end %>

test:
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbc
  username: root
  password: 
  url: jdbc:mysql://localhost/kompetansesok_test<%= ENV['DB_SUFFIX'] %>
  driver: org.gjt.mm.mysql.Driver
<% else %>
  adapter: mysql
  encoding: utf8
  database: kompetansesok_test<%= ENV['DB_SUFFIX'] %>
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
<% end %>

integration_test:
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbc
  username: root
  password: 
  url: jdbc:mysql://localhost/kompetansesok_integration_test<%= ENV['DB_SUFFIX'] %>
  driver: org.gjt.mm.mysql.Driver
<% else %>
  adapter: mysql
  encoding: utf8
  database: kompetansesok_integration_test<%= ENV['DB_SUFFIX'] %>
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
<% end %>

production:
  adapter: mysql
  encoding: utf8
  database: kompetansesok_production<%= ENV['DB_SUFFIX'] %>
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
