development:
  adapter: mysql
  encoding: utf8
  database: kompetansesok_development
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  database: kompetansesok_test
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: kompetansesok_production
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
