<% if defined?(JRUBY_VERSION) %>
<% require 'ext/mysql-connector-java-5.1.7-bin.jar' %>
<% end %>

development:
  host: localhost
  username: root
  database: kompetansesok_development<%= ENV['DB_SUFFIX'] %>
  password:
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbcmysql
  driver: org.gjt.mm.mysql.Driver
<% else %>
  adapter: mysql
<% end %>

test:
  host: localhost
  username: root
  database: kompetansesok_test<%= ENV['DB_SUFFIX'] %>
  password:
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbcmysql
  driver: org.gjt.mm.mysql.Driver
<% else %>
  adapter: mysql
<% end %>

integration_test:
  host: localhost
  username: root
  database: kompetansesok_integration_test<%= ENV['DB_SUFFIX'] %>
  password:
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbcmysql
  driver: org.gjt.mm.mysql.Driver
<% else %>
  adapter: mysql
<% end %>

production:
  host: localhost
  username: root
  database: kompetansesok
  password: kompetansesok
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbcmysql
  driver: org.gjt.mm.mysql.Driver
<% else %>
  adapter: mysql
<% end %>
