# Konfigurasjon av applikasjon
db_dumps:
  # Det som kommer etter public
  path: "db_dumps"
  count: 3

maks_detalj_rader: 50

mail:
    username: "<sett inn>"
    password: "<sett inn>"
    server: "<sett inn>"
    server_port: "<sett inn>"
    #mail addresser som mottar import rapporter, separert med ;
    rapport_mailer: "<sett inn>"
    #Kun en admin addresse
    admin_mail: "<sett inn>"

