# Konfigurasjon av applikasjon
db_dumps:
  # Det som kommer etter public
  path: "db_dumps"
  count: 3

maks_detalj_rader: 50

mail:
  domain: "udir.no"
  username: ""
  password: ""
  server: ""
  server_port: 25
  #mail addresser som mottar import rapporter, separert med ;
  to: ""
  #Kun en admin addresse
  from: ""
  from_alias: "Udir kompetansesøk"
  subject: "Rapport: Import fra GREP"
  

